<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTYs6JJI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTYs6JJI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerTYs6JJI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerTYs6JJI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerTYs6JJI\appAppKernelProdContainer([
    'container.build_hash' => 'TYs6JJI',
    'container.build_id' => '1ced67d7',
    'container.build_time' => 1712434497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTYs6JJI');
