<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEmInieo\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEmInieo/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEmInieo.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEmInieo\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerEmInieo\appAppKernelDevDebugContainer([
    'container.build_hash' => 'EmInieo',
    'container.build_id' => '2c556765',
    'container.build_time' => 1712414367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEmInieo');
